services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    env: docker
    buildCommand: ./build.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: cashworx_ovsp
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: cashworx_ovsp
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cashworx_ovsp
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cashworx_ovsp
          property: password

databases:
  - name: cashworx_ovsp
    plan: free
    databaseName: laravel
    user: laravel