services:
  - type: web
    name: cashworx-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DB_PASSWORD
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: cashworx-api
          property: host
    	- key: PORT
        value: 10000  # Render's default port
    buildCommand: docker build -t app .
    startCommand: docker run -p $PORT:80 app
